name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - uses: actions/setup-node@v4
        with:
          node-version-file: ./frontend/.node-version
      - name: Build with xc
        run: go run github.com/joerdav/xc/cmd/xc@latest build
      - uses: actions/upload-artifact@v5
        with:
          name: frontend-dist
          path: ./frontend/app-ui/dist

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v5
        with:
          name: frontend-dist
          path: ./frontend/app-ui/dist
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout=10m

  test-unit:
    name: Unit Test
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - uses: actions/download-artifact@v5
        with:
          name: frontend-dist
          path: ./frontend/app-ui/dist
      - name: Unit test with xc
        run: go run github.com/joerdav/xc/cmd/xc@latest test-unit

  test-integration:
    name: Integration Test
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - uses: actions/download-artifact@v5
        with:
          name: frontend-dist
          path: ./frontend/app-ui/dist
      - name: Integration test with xc
        run: go run github.com/joerdav/xc/cmd/xc@latest test-integration

  dependabot-automerge:
    name: Dependabot Automerge
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    needs:
      - build
      - lint
      - test-unit
      - test-integration
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        uses: dependabot/fetch-metadata@v2
        id: metadata
      - uses: actions/checkout@v5
      - name: Enable automerge
        if: |
          steps.metadata.outputs.update-type == 'version-update:semver-patch' ||
          steps.metadata.outputs.update-type == 'version-update:semver-minor'
        run: |
          gh pr merge ${{ github.event.number }} --auto --merge
        env:
          GITHUB_TOKEN: ${{ github.token }}
